name: flutter_fullpdfview_fork
description: A Pdf Viewer for Android including fit policy. Based on flutter_pdfview_fork from phaytran.
version: 1.0.3
verified publisher: phaytran.tech
homepage: https://github.com/tranvanphay/flutter_fullpdfview

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# flutter:
#   plugin:
#     androidPackage: com.github.tranvanphay.flutter_fullpdfview_fork
#     pluginClass: FlutterFullpdfviewPlugin

# flutter:
#   plugin:
#     platforms:
#       ios:
#         pluginClass: FlutterFullpdfviewPlugin
#       android:
#         package: com.github.tranvanphay.flutter_fullpdfview_fork
#         pluginClass: FlutterFullpdfviewPlugin
    